//@ts-nocheck
  // DO NOT MODIFY THIS FILE. This file is automatically generated by Tina
  export function gql(strings: TemplateStringsArray, ...args: string[]): string {
    let str = ''
    strings.forEach((string, i) => {
      str += string + (args[i] || '')
    })
    return str
  }
  export type Maybe<T> = T | null;
export type InputMaybe<T> = Maybe<T>;
export type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
export type MakeOptional<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]?: Maybe<T[SubKey]> };
export type MakeMaybe<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]: Maybe<T[SubKey]> };
export type MakeEmpty<T extends { [key: string]: unknown }, K extends keyof T> = { [_ in K]?: never };
export type Incremental<T> = T | { [P in keyof T]?: P extends ' $fragmentName' | '__typename' ? T[P] : never };
/** All built-in and custom scalars, mapped to their actual values */
export type Scalars = {
  ID: { input: string; output: string; }
  String: { input: string; output: string; }
  Boolean: { input: boolean; output: boolean; }
  Int: { input: number; output: number; }
  Float: { input: number; output: number; }
  /** References another document, used as a foreign key */
  Reference: { input: any; output: any; }
  JSON: { input: any; output: any; }
};

export type SystemInfo = {
  __typename?: 'SystemInfo';
  filename: Scalars['String']['output'];
  title?: Maybe<Scalars['String']['output']>;
  basename: Scalars['String']['output'];
  hasReferences?: Maybe<Scalars['Boolean']['output']>;
  breadcrumbs: Array<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  relativePath: Scalars['String']['output'];
  extension: Scalars['String']['output'];
  template: Scalars['String']['output'];
  collection: Collection;
};


export type SystemInfoBreadcrumbsArgs = {
  excludeExtension?: InputMaybe<Scalars['Boolean']['input']>;
};

export type Folder = {
  __typename?: 'Folder';
  name: Scalars['String']['output'];
  path: Scalars['String']['output'];
};

export type PageInfo = {
  __typename?: 'PageInfo';
  hasPreviousPage: Scalars['Boolean']['output'];
  hasNextPage: Scalars['Boolean']['output'];
  startCursor: Scalars['String']['output'];
  endCursor: Scalars['String']['output'];
};

export type Node = {
  id: Scalars['ID']['output'];
};

export type Document = {
  id: Scalars['ID']['output'];
  _sys?: Maybe<SystemInfo>;
  _values: Scalars['JSON']['output'];
};

/** A relay-compliant pagination connection */
export type Connection = {
  totalCount: Scalars['Float']['output'];
  pageInfo: PageInfo;
};

export type Query = {
  __typename?: 'Query';
  getOptimizedQuery?: Maybe<Scalars['String']['output']>;
  collection: Collection;
  collections: Array<Collection>;
  node: Node;
  document: DocumentNode;
  homePage: HomePage;
  homePageConnection: HomePageConnection;
  activitiesPage: ActivitiesPage;
  activitiesPageConnection: ActivitiesPageConnection;
  stayingPage: StayingPage;
  stayingPageConnection: StayingPageConnection;
  islandPage: IslandPage;
  islandPageConnection: IslandPageConnection;
  ritualsPage: RitualsPage;
  ritualsPageConnection: RitualsPageConnection;
  contactPage: ContactPage;
  contactPageConnection: ContactPageConnection;
};


export type QueryGetOptimizedQueryArgs = {
  queryString: Scalars['String']['input'];
};


export type QueryCollectionArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
};


export type QueryNodeArgs = {
  id?: InputMaybe<Scalars['String']['input']>;
};


export type QueryDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryHomePageArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryHomePageConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<HomePageFilter>;
};


export type QueryActivitiesPageArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryActivitiesPageConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<ActivitiesPageFilter>;
};


export type QueryStayingPageArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryStayingPageConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<StayingPageFilter>;
};


export type QueryIslandPageArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryIslandPageConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<IslandPageFilter>;
};


export type QueryRitualsPageArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryRitualsPageConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<RitualsPageFilter>;
};


export type QueryContactPageArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryContactPageConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<ContactPageFilter>;
};

export type DocumentFilter = {
  homePage?: InputMaybe<HomePageFilter>;
  activitiesPage?: InputMaybe<ActivitiesPageFilter>;
  stayingPage?: InputMaybe<StayingPageFilter>;
  islandPage?: InputMaybe<IslandPageFilter>;
  ritualsPage?: InputMaybe<RitualsPageFilter>;
  contactPage?: InputMaybe<ContactPageFilter>;
};

export type DocumentConnectionEdges = {
  __typename?: 'DocumentConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<DocumentNode>;
};

export type DocumentConnection = Connection & {
  __typename?: 'DocumentConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<DocumentConnectionEdges>>>;
};

export type Collection = {
  __typename?: 'Collection';
  name: Scalars['String']['output'];
  slug: Scalars['String']['output'];
  label?: Maybe<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  format?: Maybe<Scalars['String']['output']>;
  matches?: Maybe<Scalars['String']['output']>;
  templates?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  fields?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  documents: DocumentConnection;
};


export type CollectionDocumentsArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<DocumentFilter>;
  folder?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentNode = HomePage | ActivitiesPage | StayingPage | IslandPage | RitualsPage | ContactPage | Folder;

export type HomePageHero = {
  __typename?: 'HomePageHero';
  image?: Maybe<Scalars['String']['output']>;
  imageAlt?: Maybe<Scalars['String']['output']>;
  title: Scalars['String']['output'];
  subtitle?: Maybe<Scalars['String']['output']>;
};

export type HomePageMapCta = {
  __typename?: 'HomePageMapCta';
  heading?: Maybe<Scalars['String']['output']>;
  description?: Maybe<Scalars['JSON']['output']>;
};

export type HomePageFirstImage = {
  __typename?: 'HomePageFirstImage';
  src?: Maybe<Scalars['String']['output']>;
  alt?: Maybe<Scalars['String']['output']>;
};

export type HomePageSecondImage = {
  __typename?: 'HomePageSecondImage';
  src?: Maybe<Scalars['String']['output']>;
  alt?: Maybe<Scalars['String']['output']>;
};

export type HomePage = Node & Document & {
  __typename?: 'HomePage';
  hero?: Maybe<HomePageHero>;
  poeticParagraphs?: Maybe<Scalars['JSON']['output']>;
  secondParagraphs?: Maybe<Scalars['JSON']['output']>;
  pullQuote?: Maybe<Scalars['String']['output']>;
  mapCta?: Maybe<HomePageMapCta>;
  firstImage?: Maybe<HomePageFirstImage>;
  secondImage?: Maybe<HomePageSecondImage>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type ImageFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type StringFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type HomePageHeroFilter = {
  image?: InputMaybe<ImageFilter>;
  imageAlt?: InputMaybe<StringFilter>;
  title?: InputMaybe<StringFilter>;
  subtitle?: InputMaybe<StringFilter>;
};

export type RichTextFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
};

export type HomePageMapCtaFilter = {
  heading?: InputMaybe<StringFilter>;
  description?: InputMaybe<RichTextFilter>;
};

export type HomePageFirstImageFilter = {
  src?: InputMaybe<ImageFilter>;
  alt?: InputMaybe<StringFilter>;
};

export type HomePageSecondImageFilter = {
  src?: InputMaybe<ImageFilter>;
  alt?: InputMaybe<StringFilter>;
};

export type HomePageFilter = {
  hero?: InputMaybe<HomePageHeroFilter>;
  poeticParagraphs?: InputMaybe<RichTextFilter>;
  secondParagraphs?: InputMaybe<RichTextFilter>;
  pullQuote?: InputMaybe<StringFilter>;
  mapCta?: InputMaybe<HomePageMapCtaFilter>;
  firstImage?: InputMaybe<HomePageFirstImageFilter>;
  secondImage?: InputMaybe<HomePageSecondImageFilter>;
};

export type HomePageConnectionEdges = {
  __typename?: 'HomePageConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<HomePage>;
};

export type HomePageConnection = Connection & {
  __typename?: 'HomePageConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<HomePageConnectionEdges>>>;
};

export type ActivitiesPageHero = {
  __typename?: 'ActivitiesPageHero';
  image?: Maybe<Scalars['String']['output']>;
  imageAlt?: Maybe<Scalars['String']['output']>;
  title: Scalars['String']['output'];
  subtitle?: Maybe<Scalars['String']['output']>;
};

export type ActivitiesPageWaterSectionItems = {
  __typename?: 'ActivitiesPageWaterSectionItems';
  image?: Maybe<Scalars['String']['output']>;
  imageAlt?: Maybe<Scalars['String']['output']>;
  title?: Maybe<Scalars['String']['output']>;
  description?: Maybe<Scalars['String']['output']>;
};

export type ActivitiesPageWaterSection = {
  __typename?: 'ActivitiesPageWaterSection';
  heading?: Maybe<Scalars['String']['output']>;
  items?: Maybe<Array<Maybe<ActivitiesPageWaterSectionItems>>>;
};

export type ActivitiesPageLandSectionItems = {
  __typename?: 'ActivitiesPageLandSectionItems';
  image?: Maybe<Scalars['String']['output']>;
  imageAlt?: Maybe<Scalars['String']['output']>;
  title?: Maybe<Scalars['String']['output']>;
  description?: Maybe<Scalars['String']['output']>;
};

export type ActivitiesPageLandSection = {
  __typename?: 'ActivitiesPageLandSection';
  heading?: Maybe<Scalars['String']['output']>;
  items?: Maybe<Array<Maybe<ActivitiesPageLandSectionItems>>>;
};

export type ActivitiesPageRegionSectionPlaces = {
  __typename?: 'ActivitiesPageRegionSectionPlaces';
  name?: Maybe<Scalars['String']['output']>;
  description?: Maybe<Scalars['JSON']['output']>;
};

export type ActivitiesPageRegionSection = {
  __typename?: 'ActivitiesPageRegionSection';
  heading?: Maybe<Scalars['String']['output']>;
  places?: Maybe<Array<Maybe<ActivitiesPageRegionSectionPlaces>>>;
  image?: Maybe<Scalars['String']['output']>;
  imageAlt?: Maybe<Scalars['String']['output']>;
};

export type ActivitiesPageFireSection = {
  __typename?: 'ActivitiesPageFireSection';
  heading?: Maybe<Scalars['String']['output']>;
  text?: Maybe<Scalars['JSON']['output']>;
  closingImage?: Maybe<Scalars['String']['output']>;
  closingImageAlt?: Maybe<Scalars['String']['output']>;
};

export type ActivitiesPage = Node & Document & {
  __typename?: 'ActivitiesPage';
  hero?: Maybe<ActivitiesPageHero>;
  intro?: Maybe<Scalars['JSON']['output']>;
  waterSection?: Maybe<ActivitiesPageWaterSection>;
  landSection?: Maybe<ActivitiesPageLandSection>;
  regionSection?: Maybe<ActivitiesPageRegionSection>;
  fireSection?: Maybe<ActivitiesPageFireSection>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type ActivitiesPageHeroFilter = {
  image?: InputMaybe<ImageFilter>;
  imageAlt?: InputMaybe<StringFilter>;
  title?: InputMaybe<StringFilter>;
  subtitle?: InputMaybe<StringFilter>;
};

export type ActivitiesPageWaterSectionItemsFilter = {
  image?: InputMaybe<ImageFilter>;
  imageAlt?: InputMaybe<StringFilter>;
  title?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
};

export type ActivitiesPageWaterSectionFilter = {
  heading?: InputMaybe<StringFilter>;
  items?: InputMaybe<ActivitiesPageWaterSectionItemsFilter>;
};

export type ActivitiesPageLandSectionItemsFilter = {
  image?: InputMaybe<ImageFilter>;
  imageAlt?: InputMaybe<StringFilter>;
  title?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
};

export type ActivitiesPageLandSectionFilter = {
  heading?: InputMaybe<StringFilter>;
  items?: InputMaybe<ActivitiesPageLandSectionItemsFilter>;
};

export type ActivitiesPageRegionSectionPlacesFilter = {
  name?: InputMaybe<StringFilter>;
  description?: InputMaybe<RichTextFilter>;
};

export type ActivitiesPageRegionSectionFilter = {
  heading?: InputMaybe<StringFilter>;
  places?: InputMaybe<ActivitiesPageRegionSectionPlacesFilter>;
  image?: InputMaybe<ImageFilter>;
  imageAlt?: InputMaybe<StringFilter>;
};

export type ActivitiesPageFireSectionFilter = {
  heading?: InputMaybe<StringFilter>;
  text?: InputMaybe<RichTextFilter>;
  closingImage?: InputMaybe<ImageFilter>;
  closingImageAlt?: InputMaybe<StringFilter>;
};

export type ActivitiesPageFilter = {
  hero?: InputMaybe<ActivitiesPageHeroFilter>;
  intro?: InputMaybe<RichTextFilter>;
  waterSection?: InputMaybe<ActivitiesPageWaterSectionFilter>;
  landSection?: InputMaybe<ActivitiesPageLandSectionFilter>;
  regionSection?: InputMaybe<ActivitiesPageRegionSectionFilter>;
  fireSection?: InputMaybe<ActivitiesPageFireSectionFilter>;
};

export type ActivitiesPageConnectionEdges = {
  __typename?: 'ActivitiesPageConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<ActivitiesPage>;
};

export type ActivitiesPageConnection = Connection & {
  __typename?: 'ActivitiesPageConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<ActivitiesPageConnectionEdges>>>;
};

export type StayingPageHero = {
  __typename?: 'StayingPageHero';
  image?: Maybe<Scalars['String']['output']>;
  imageAlt?: Maybe<Scalars['String']['output']>;
  title: Scalars['String']['output'];
  subtitle?: Maybe<Scalars['String']['output']>;
};

export type StayingPageBuildingImages = {
  __typename?: 'StayingPageBuildingImages';
  src?: Maybe<Scalars['String']['output']>;
  alt?: Maybe<Scalars['String']['output']>;
};

export type StayingPageSleepingSection = {
  __typename?: 'StayingPageSleepingSection';
  heading?: Maybe<Scalars['String']['output']>;
  paragraphs?: Maybe<Scalars['JSON']['output']>;
  image?: Maybe<Scalars['String']['output']>;
  imageAlt?: Maybe<Scalars['String']['output']>;
};

export type StayingPageSharedSpacesSection = {
  __typename?: 'StayingPageSharedSpacesSection';
  heading?: Maybe<Scalars['String']['output']>;
  paragraphs?: Maybe<Scalars['JSON']['output']>;
};

export type StayingPageGalleryImages = {
  __typename?: 'StayingPageGalleryImages';
  src?: Maybe<Scalars['String']['output']>;
  alt?: Maybe<Scalars['String']['output']>;
};

export type StayingPageGroupSpacesSection = {
  __typename?: 'StayingPageGroupSpacesSection';
  heading?: Maybe<Scalars['String']['output']>;
  paragraphs?: Maybe<Scalars['JSON']['output']>;
};

export type StayingPageClosingImage = {
  __typename?: 'StayingPageClosingImage';
  src?: Maybe<Scalars['String']['output']>;
  alt?: Maybe<Scalars['String']['output']>;
};

export type StayingPage = Node & Document & {
  __typename?: 'StayingPage';
  hero?: Maybe<StayingPageHero>;
  intro?: Maybe<Scalars['JSON']['output']>;
  buildingImages?: Maybe<Array<Maybe<StayingPageBuildingImages>>>;
  sleepingSection?: Maybe<StayingPageSleepingSection>;
  sharedSpacesSection?: Maybe<StayingPageSharedSpacesSection>;
  galleryImages?: Maybe<Array<Maybe<StayingPageGalleryImages>>>;
  groupSpacesSection?: Maybe<StayingPageGroupSpacesSection>;
  closingImage?: Maybe<StayingPageClosingImage>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type StayingPageHeroFilter = {
  image?: InputMaybe<ImageFilter>;
  imageAlt?: InputMaybe<StringFilter>;
  title?: InputMaybe<StringFilter>;
  subtitle?: InputMaybe<StringFilter>;
};

export type StayingPageBuildingImagesFilter = {
  src?: InputMaybe<ImageFilter>;
  alt?: InputMaybe<StringFilter>;
};

export type StayingPageSleepingSectionFilter = {
  heading?: InputMaybe<StringFilter>;
  paragraphs?: InputMaybe<RichTextFilter>;
  image?: InputMaybe<ImageFilter>;
  imageAlt?: InputMaybe<StringFilter>;
};

export type StayingPageSharedSpacesSectionFilter = {
  heading?: InputMaybe<StringFilter>;
  paragraphs?: InputMaybe<RichTextFilter>;
};

export type StayingPageGalleryImagesFilter = {
  src?: InputMaybe<ImageFilter>;
  alt?: InputMaybe<StringFilter>;
};

export type StayingPageGroupSpacesSectionFilter = {
  heading?: InputMaybe<StringFilter>;
  paragraphs?: InputMaybe<RichTextFilter>;
};

export type StayingPageClosingImageFilter = {
  src?: InputMaybe<ImageFilter>;
  alt?: InputMaybe<StringFilter>;
};

export type StayingPageFilter = {
  hero?: InputMaybe<StayingPageHeroFilter>;
  intro?: InputMaybe<RichTextFilter>;
  buildingImages?: InputMaybe<StayingPageBuildingImagesFilter>;
  sleepingSection?: InputMaybe<StayingPageSleepingSectionFilter>;
  sharedSpacesSection?: InputMaybe<StayingPageSharedSpacesSectionFilter>;
  galleryImages?: InputMaybe<StayingPageGalleryImagesFilter>;
  groupSpacesSection?: InputMaybe<StayingPageGroupSpacesSectionFilter>;
  closingImage?: InputMaybe<StayingPageClosingImageFilter>;
};

export type StayingPageConnectionEdges = {
  __typename?: 'StayingPageConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<StayingPage>;
};

export type StayingPageConnection = Connection & {
  __typename?: 'StayingPageConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<StayingPageConnectionEdges>>>;
};

export type IslandPageHero = {
  __typename?: 'IslandPageHero';
  image?: Maybe<Scalars['String']['output']>;
  imageAlt?: Maybe<Scalars['String']['output']>;
  title: Scalars['String']['output'];
  subtitle?: Maybe<Scalars['String']['output']>;
};

export type IslandPageClimateSection = {
  __typename?: 'IslandPageClimateSection';
  heading?: Maybe<Scalars['String']['output']>;
  paragraphs?: Maybe<Scalars['JSON']['output']>;
  image?: Maybe<Scalars['String']['output']>;
  imageAlt?: Maybe<Scalars['String']['output']>;
};

export type IslandPageMountainsSection = {
  __typename?: 'IslandPageMountainsSection';
  heading?: Maybe<Scalars['String']['output']>;
  paragraphs?: Maybe<Scalars['JSON']['output']>;
  image?: Maybe<Scalars['String']['output']>;
  imageAlt?: Maybe<Scalars['String']['output']>;
};

export type IslandPageWildlifeSection = {
  __typename?: 'IslandPageWildlifeSection';
  heading?: Maybe<Scalars['String']['output']>;
  paragraphs?: Maybe<Scalars['JSON']['output']>;
  image?: Maybe<Scalars['String']['output']>;
  imageAlt?: Maybe<Scalars['String']['output']>;
};

export type IslandPage = Node & Document & {
  __typename?: 'IslandPage';
  hero?: Maybe<IslandPageHero>;
  intro?: Maybe<Scalars['JSON']['output']>;
  climateSection?: Maybe<IslandPageClimateSection>;
  mountainsSection?: Maybe<IslandPageMountainsSection>;
  wildlifeSection?: Maybe<IslandPageWildlifeSection>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type IslandPageHeroFilter = {
  image?: InputMaybe<ImageFilter>;
  imageAlt?: InputMaybe<StringFilter>;
  title?: InputMaybe<StringFilter>;
  subtitle?: InputMaybe<StringFilter>;
};

export type IslandPageClimateSectionFilter = {
  heading?: InputMaybe<StringFilter>;
  paragraphs?: InputMaybe<RichTextFilter>;
  image?: InputMaybe<ImageFilter>;
  imageAlt?: InputMaybe<StringFilter>;
};

export type IslandPageMountainsSectionFilter = {
  heading?: InputMaybe<StringFilter>;
  paragraphs?: InputMaybe<RichTextFilter>;
  image?: InputMaybe<ImageFilter>;
  imageAlt?: InputMaybe<StringFilter>;
};

export type IslandPageWildlifeSectionFilter = {
  heading?: InputMaybe<StringFilter>;
  paragraphs?: InputMaybe<RichTextFilter>;
  image?: InputMaybe<ImageFilter>;
  imageAlt?: InputMaybe<StringFilter>;
};

export type IslandPageFilter = {
  hero?: InputMaybe<IslandPageHeroFilter>;
  intro?: InputMaybe<RichTextFilter>;
  climateSection?: InputMaybe<IslandPageClimateSectionFilter>;
  mountainsSection?: InputMaybe<IslandPageMountainsSectionFilter>;
  wildlifeSection?: InputMaybe<IslandPageWildlifeSectionFilter>;
};

export type IslandPageConnectionEdges = {
  __typename?: 'IslandPageConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<IslandPage>;
};

export type IslandPageConnection = Connection & {
  __typename?: 'IslandPageConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<IslandPageConnectionEdges>>>;
};

export type RitualsPageHero = {
  __typename?: 'RitualsPageHero';
  image?: Maybe<Scalars['String']['output']>;
  imageAlt?: Maybe<Scalars['String']['output']>;
  title: Scalars['String']['output'];
  subtitle?: Maybe<Scalars['String']['output']>;
};

export type RitualsPageMidImage = {
  __typename?: 'RitualsPageMidImage';
  src?: Maybe<Scalars['String']['output']>;
  alt?: Maybe<Scalars['String']['output']>;
};

export type RitualsPageShapedTogetherSection = {
  __typename?: 'RitualsPageShapedTogetherSection';
  heading?: Maybe<Scalars['String']['output']>;
  paragraphs?: Maybe<Scalars['JSON']['output']>;
  image?: Maybe<Scalars['String']['output']>;
  imageAlt?: Maybe<Scalars['String']['output']>;
};

export type RitualsPageGatheringsSection = {
  __typename?: 'RitualsPageGatheringsSection';
  heading?: Maybe<Scalars['String']['output']>;
  paragraphs?: Maybe<Scalars['JSON']['output']>;
  pullQuote?: Maybe<Scalars['String']['output']>;
};

export type RitualsPage = Node & Document & {
  __typename?: 'RitualsPage';
  hero?: Maybe<RitualsPageHero>;
  intro?: Maybe<Scalars['JSON']['output']>;
  midImage?: Maybe<RitualsPageMidImage>;
  secondParagraphs?: Maybe<Scalars['JSON']['output']>;
  shapedTogetherSection?: Maybe<RitualsPageShapedTogetherSection>;
  gatheringsSection?: Maybe<RitualsPageGatheringsSection>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type RitualsPageHeroFilter = {
  image?: InputMaybe<ImageFilter>;
  imageAlt?: InputMaybe<StringFilter>;
  title?: InputMaybe<StringFilter>;
  subtitle?: InputMaybe<StringFilter>;
};

export type RitualsPageMidImageFilter = {
  src?: InputMaybe<ImageFilter>;
  alt?: InputMaybe<StringFilter>;
};

export type RitualsPageShapedTogetherSectionFilter = {
  heading?: InputMaybe<StringFilter>;
  paragraphs?: InputMaybe<RichTextFilter>;
  image?: InputMaybe<ImageFilter>;
  imageAlt?: InputMaybe<StringFilter>;
};

export type RitualsPageGatheringsSectionFilter = {
  heading?: InputMaybe<StringFilter>;
  paragraphs?: InputMaybe<RichTextFilter>;
  pullQuote?: InputMaybe<StringFilter>;
};

export type RitualsPageFilter = {
  hero?: InputMaybe<RitualsPageHeroFilter>;
  intro?: InputMaybe<RichTextFilter>;
  midImage?: InputMaybe<RitualsPageMidImageFilter>;
  secondParagraphs?: InputMaybe<RichTextFilter>;
  shapedTogetherSection?: InputMaybe<RitualsPageShapedTogetherSectionFilter>;
  gatheringsSection?: InputMaybe<RitualsPageGatheringsSectionFilter>;
};

export type RitualsPageConnectionEdges = {
  __typename?: 'RitualsPageConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<RitualsPage>;
};

export type RitualsPageConnection = Connection & {
  __typename?: 'RitualsPageConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<RitualsPageConnectionEdges>>>;
};

export type ContactPageHero = {
  __typename?: 'ContactPageHero';
  image?: Maybe<Scalars['String']['output']>;
  imageAlt?: Maybe<Scalars['String']['output']>;
  title: Scalars['String']['output'];
  subtitle?: Maybe<Scalars['String']['output']>;
};

export type ContactPage = Node & Document & {
  __typename?: 'ContactPage';
  hero?: Maybe<ContactPageHero>;
  introText?: Maybe<Scalars['String']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type ContactPageHeroFilter = {
  image?: InputMaybe<ImageFilter>;
  imageAlt?: InputMaybe<StringFilter>;
  title?: InputMaybe<StringFilter>;
  subtitle?: InputMaybe<StringFilter>;
};

export type ContactPageFilter = {
  hero?: InputMaybe<ContactPageHeroFilter>;
  introText?: InputMaybe<StringFilter>;
};

export type ContactPageConnectionEdges = {
  __typename?: 'ContactPageConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<ContactPage>;
};

export type ContactPageConnection = Connection & {
  __typename?: 'ContactPageConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<ContactPageConnectionEdges>>>;
};

export type Mutation = {
  __typename?: 'Mutation';
  addPendingDocument: DocumentNode;
  updateDocument: DocumentNode;
  deleteDocument: DocumentNode;
  createDocument: DocumentNode;
  createFolder: DocumentNode;
  updateHomePage: HomePage;
  createHomePage: HomePage;
  updateActivitiesPage: ActivitiesPage;
  createActivitiesPage: ActivitiesPage;
  updateStayingPage: StayingPage;
  createStayingPage: StayingPage;
  updateIslandPage: IslandPage;
  createIslandPage: IslandPage;
  updateRitualsPage: RitualsPage;
  createRitualsPage: RitualsPage;
  updateContactPage: ContactPage;
  createContactPage: ContactPage;
};


export type MutationAddPendingDocumentArgs = {
  collection: Scalars['String']['input'];
  relativePath: Scalars['String']['input'];
  template?: InputMaybe<Scalars['String']['input']>;
};


export type MutationUpdateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentUpdateMutation;
};


export type MutationDeleteDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationCreateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentMutation;
};


export type MutationCreateFolderArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationUpdateHomePageArgs = {
  relativePath: Scalars['String']['input'];
  params: HomePageMutation;
};


export type MutationCreateHomePageArgs = {
  relativePath: Scalars['String']['input'];
  params: HomePageMutation;
};


export type MutationUpdateActivitiesPageArgs = {
  relativePath: Scalars['String']['input'];
  params: ActivitiesPageMutation;
};


export type MutationCreateActivitiesPageArgs = {
  relativePath: Scalars['String']['input'];
  params: ActivitiesPageMutation;
};


export type MutationUpdateStayingPageArgs = {
  relativePath: Scalars['String']['input'];
  params: StayingPageMutation;
};


export type MutationCreateStayingPageArgs = {
  relativePath: Scalars['String']['input'];
  params: StayingPageMutation;
};


export type MutationUpdateIslandPageArgs = {
  relativePath: Scalars['String']['input'];
  params: IslandPageMutation;
};


export type MutationCreateIslandPageArgs = {
  relativePath: Scalars['String']['input'];
  params: IslandPageMutation;
};


export type MutationUpdateRitualsPageArgs = {
  relativePath: Scalars['String']['input'];
  params: RitualsPageMutation;
};


export type MutationCreateRitualsPageArgs = {
  relativePath: Scalars['String']['input'];
  params: RitualsPageMutation;
};


export type MutationUpdateContactPageArgs = {
  relativePath: Scalars['String']['input'];
  params: ContactPageMutation;
};


export type MutationCreateContactPageArgs = {
  relativePath: Scalars['String']['input'];
  params: ContactPageMutation;
};

export type DocumentUpdateMutation = {
  homePage?: InputMaybe<HomePageMutation>;
  activitiesPage?: InputMaybe<ActivitiesPageMutation>;
  stayingPage?: InputMaybe<StayingPageMutation>;
  islandPage?: InputMaybe<IslandPageMutation>;
  ritualsPage?: InputMaybe<RitualsPageMutation>;
  contactPage?: InputMaybe<ContactPageMutation>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentMutation = {
  homePage?: InputMaybe<HomePageMutation>;
  activitiesPage?: InputMaybe<ActivitiesPageMutation>;
  stayingPage?: InputMaybe<StayingPageMutation>;
  islandPage?: InputMaybe<IslandPageMutation>;
  ritualsPage?: InputMaybe<RitualsPageMutation>;
  contactPage?: InputMaybe<ContactPageMutation>;
};

export type HomePageHeroMutation = {
  image?: InputMaybe<Scalars['String']['input']>;
  imageAlt?: InputMaybe<Scalars['String']['input']>;
  title?: InputMaybe<Scalars['String']['input']>;
  subtitle?: InputMaybe<Scalars['String']['input']>;
};

export type HomePageMapCtaMutation = {
  heading?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['JSON']['input']>;
};

export type HomePageFirstImageMutation = {
  src?: InputMaybe<Scalars['String']['input']>;
  alt?: InputMaybe<Scalars['String']['input']>;
};

export type HomePageSecondImageMutation = {
  src?: InputMaybe<Scalars['String']['input']>;
  alt?: InputMaybe<Scalars['String']['input']>;
};

export type HomePageMutation = {
  hero?: InputMaybe<HomePageHeroMutation>;
  poeticParagraphs?: InputMaybe<Scalars['JSON']['input']>;
  secondParagraphs?: InputMaybe<Scalars['JSON']['input']>;
  pullQuote?: InputMaybe<Scalars['String']['input']>;
  mapCta?: InputMaybe<HomePageMapCtaMutation>;
  firstImage?: InputMaybe<HomePageFirstImageMutation>;
  secondImage?: InputMaybe<HomePageSecondImageMutation>;
};

export type ActivitiesPageHeroMutation = {
  image?: InputMaybe<Scalars['String']['input']>;
  imageAlt?: InputMaybe<Scalars['String']['input']>;
  title?: InputMaybe<Scalars['String']['input']>;
  subtitle?: InputMaybe<Scalars['String']['input']>;
};

export type ActivitiesPageWaterSectionItemsMutation = {
  image?: InputMaybe<Scalars['String']['input']>;
  imageAlt?: InputMaybe<Scalars['String']['input']>;
  title?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
};

export type ActivitiesPageWaterSectionMutation = {
  heading?: InputMaybe<Scalars['String']['input']>;
  items?: InputMaybe<Array<InputMaybe<ActivitiesPageWaterSectionItemsMutation>>>;
};

export type ActivitiesPageLandSectionItemsMutation = {
  image?: InputMaybe<Scalars['String']['input']>;
  imageAlt?: InputMaybe<Scalars['String']['input']>;
  title?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
};

export type ActivitiesPageLandSectionMutation = {
  heading?: InputMaybe<Scalars['String']['input']>;
  items?: InputMaybe<Array<InputMaybe<ActivitiesPageLandSectionItemsMutation>>>;
};

export type ActivitiesPageRegionSectionPlacesMutation = {
  name?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['JSON']['input']>;
};

export type ActivitiesPageRegionSectionMutation = {
  heading?: InputMaybe<Scalars['String']['input']>;
  places?: InputMaybe<Array<InputMaybe<ActivitiesPageRegionSectionPlacesMutation>>>;
  image?: InputMaybe<Scalars['String']['input']>;
  imageAlt?: InputMaybe<Scalars['String']['input']>;
};

export type ActivitiesPageFireSectionMutation = {
  heading?: InputMaybe<Scalars['String']['input']>;
  text?: InputMaybe<Scalars['JSON']['input']>;
  closingImage?: InputMaybe<Scalars['String']['input']>;
  closingImageAlt?: InputMaybe<Scalars['String']['input']>;
};

export type ActivitiesPageMutation = {
  hero?: InputMaybe<ActivitiesPageHeroMutation>;
  intro?: InputMaybe<Scalars['JSON']['input']>;
  waterSection?: InputMaybe<ActivitiesPageWaterSectionMutation>;
  landSection?: InputMaybe<ActivitiesPageLandSectionMutation>;
  regionSection?: InputMaybe<ActivitiesPageRegionSectionMutation>;
  fireSection?: InputMaybe<ActivitiesPageFireSectionMutation>;
};

export type StayingPageHeroMutation = {
  image?: InputMaybe<Scalars['String']['input']>;
  imageAlt?: InputMaybe<Scalars['String']['input']>;
  title?: InputMaybe<Scalars['String']['input']>;
  subtitle?: InputMaybe<Scalars['String']['input']>;
};

export type StayingPageBuildingImagesMutation = {
  src?: InputMaybe<Scalars['String']['input']>;
  alt?: InputMaybe<Scalars['String']['input']>;
};

export type StayingPageSleepingSectionMutation = {
  heading?: InputMaybe<Scalars['String']['input']>;
  paragraphs?: InputMaybe<Scalars['JSON']['input']>;
  image?: InputMaybe<Scalars['String']['input']>;
  imageAlt?: InputMaybe<Scalars['String']['input']>;
};

export type StayingPageSharedSpacesSectionMutation = {
  heading?: InputMaybe<Scalars['String']['input']>;
  paragraphs?: InputMaybe<Scalars['JSON']['input']>;
};

export type StayingPageGalleryImagesMutation = {
  src?: InputMaybe<Scalars['String']['input']>;
  alt?: InputMaybe<Scalars['String']['input']>;
};

export type StayingPageGroupSpacesSectionMutation = {
  heading?: InputMaybe<Scalars['String']['input']>;
  paragraphs?: InputMaybe<Scalars['JSON']['input']>;
};

export type StayingPageClosingImageMutation = {
  src?: InputMaybe<Scalars['String']['input']>;
  alt?: InputMaybe<Scalars['String']['input']>;
};

export type StayingPageMutation = {
  hero?: InputMaybe<StayingPageHeroMutation>;
  intro?: InputMaybe<Scalars['JSON']['input']>;
  buildingImages?: InputMaybe<Array<InputMaybe<StayingPageBuildingImagesMutation>>>;
  sleepingSection?: InputMaybe<StayingPageSleepingSectionMutation>;
  sharedSpacesSection?: InputMaybe<StayingPageSharedSpacesSectionMutation>;
  galleryImages?: InputMaybe<Array<InputMaybe<StayingPageGalleryImagesMutation>>>;
  groupSpacesSection?: InputMaybe<StayingPageGroupSpacesSectionMutation>;
  closingImage?: InputMaybe<StayingPageClosingImageMutation>;
};

export type IslandPageHeroMutation = {
  image?: InputMaybe<Scalars['String']['input']>;
  imageAlt?: InputMaybe<Scalars['String']['input']>;
  title?: InputMaybe<Scalars['String']['input']>;
  subtitle?: InputMaybe<Scalars['String']['input']>;
};

export type IslandPageClimateSectionMutation = {
  heading?: InputMaybe<Scalars['String']['input']>;
  paragraphs?: InputMaybe<Scalars['JSON']['input']>;
  image?: InputMaybe<Scalars['String']['input']>;
  imageAlt?: InputMaybe<Scalars['String']['input']>;
};

export type IslandPageMountainsSectionMutation = {
  heading?: InputMaybe<Scalars['String']['input']>;
  paragraphs?: InputMaybe<Scalars['JSON']['input']>;
  image?: InputMaybe<Scalars['String']['input']>;
  imageAlt?: InputMaybe<Scalars['String']['input']>;
};

export type IslandPageWildlifeSectionMutation = {
  heading?: InputMaybe<Scalars['String']['input']>;
  paragraphs?: InputMaybe<Scalars['JSON']['input']>;
  image?: InputMaybe<Scalars['String']['input']>;
  imageAlt?: InputMaybe<Scalars['String']['input']>;
};

export type IslandPageMutation = {
  hero?: InputMaybe<IslandPageHeroMutation>;
  intro?: InputMaybe<Scalars['JSON']['input']>;
  climateSection?: InputMaybe<IslandPageClimateSectionMutation>;
  mountainsSection?: InputMaybe<IslandPageMountainsSectionMutation>;
  wildlifeSection?: InputMaybe<IslandPageWildlifeSectionMutation>;
};

export type RitualsPageHeroMutation = {
  image?: InputMaybe<Scalars['String']['input']>;
  imageAlt?: InputMaybe<Scalars['String']['input']>;
  title?: InputMaybe<Scalars['String']['input']>;
  subtitle?: InputMaybe<Scalars['String']['input']>;
};

export type RitualsPageMidImageMutation = {
  src?: InputMaybe<Scalars['String']['input']>;
  alt?: InputMaybe<Scalars['String']['input']>;
};

export type RitualsPageShapedTogetherSectionMutation = {
  heading?: InputMaybe<Scalars['String']['input']>;
  paragraphs?: InputMaybe<Scalars['JSON']['input']>;
  image?: InputMaybe<Scalars['String']['input']>;
  imageAlt?: InputMaybe<Scalars['String']['input']>;
};

export type RitualsPageGatheringsSectionMutation = {
  heading?: InputMaybe<Scalars['String']['input']>;
  paragraphs?: InputMaybe<Scalars['JSON']['input']>;
  pullQuote?: InputMaybe<Scalars['String']['input']>;
};

export type RitualsPageMutation = {
  hero?: InputMaybe<RitualsPageHeroMutation>;
  intro?: InputMaybe<Scalars['JSON']['input']>;
  midImage?: InputMaybe<RitualsPageMidImageMutation>;
  secondParagraphs?: InputMaybe<Scalars['JSON']['input']>;
  shapedTogetherSection?: InputMaybe<RitualsPageShapedTogetherSectionMutation>;
  gatheringsSection?: InputMaybe<RitualsPageGatheringsSectionMutation>;
};

export type ContactPageHeroMutation = {
  image?: InputMaybe<Scalars['String']['input']>;
  imageAlt?: InputMaybe<Scalars['String']['input']>;
  title?: InputMaybe<Scalars['String']['input']>;
  subtitle?: InputMaybe<Scalars['String']['input']>;
};

export type ContactPageMutation = {
  hero?: InputMaybe<ContactPageHeroMutation>;
  introText?: InputMaybe<Scalars['String']['input']>;
};

export type HomePagePartsFragment = { __typename: 'HomePage', poeticParagraphs?: any | null, secondParagraphs?: any | null, pullQuote?: string | null, hero?: { __typename: 'HomePageHero', image?: string | null, imageAlt?: string | null, title: string, subtitle?: string | null } | null, mapCta?: { __typename: 'HomePageMapCta', heading?: string | null, description?: any | null } | null, firstImage?: { __typename: 'HomePageFirstImage', src?: string | null, alt?: string | null } | null, secondImage?: { __typename: 'HomePageSecondImage', src?: string | null, alt?: string | null } | null };

export type ActivitiesPagePartsFragment = { __typename: 'ActivitiesPage', intro?: any | null, hero?: { __typename: 'ActivitiesPageHero', image?: string | null, imageAlt?: string | null, title: string, subtitle?: string | null } | null, waterSection?: { __typename: 'ActivitiesPageWaterSection', heading?: string | null, items?: Array<{ __typename: 'ActivitiesPageWaterSectionItems', image?: string | null, imageAlt?: string | null, title?: string | null, description?: string | null } | null> | null } | null, landSection?: { __typename: 'ActivitiesPageLandSection', heading?: string | null, items?: Array<{ __typename: 'ActivitiesPageLandSectionItems', image?: string | null, imageAlt?: string | null, title?: string | null, description?: string | null } | null> | null } | null, regionSection?: { __typename: 'ActivitiesPageRegionSection', heading?: string | null, image?: string | null, imageAlt?: string | null, places?: Array<{ __typename: 'ActivitiesPageRegionSectionPlaces', name?: string | null, description?: any | null } | null> | null } | null, fireSection?: { __typename: 'ActivitiesPageFireSection', heading?: string | null, text?: any | null, closingImage?: string | null, closingImageAlt?: string | null } | null };

export type StayingPagePartsFragment = { __typename: 'StayingPage', intro?: any | null, hero?: { __typename: 'StayingPageHero', image?: string | null, imageAlt?: string | null, title: string, subtitle?: string | null } | null, buildingImages?: Array<{ __typename: 'StayingPageBuildingImages', src?: string | null, alt?: string | null } | null> | null, sleepingSection?: { __typename: 'StayingPageSleepingSection', heading?: string | null, paragraphs?: any | null, image?: string | null, imageAlt?: string | null } | null, sharedSpacesSection?: { __typename: 'StayingPageSharedSpacesSection', heading?: string | null, paragraphs?: any | null } | null, galleryImages?: Array<{ __typename: 'StayingPageGalleryImages', src?: string | null, alt?: string | null } | null> | null, groupSpacesSection?: { __typename: 'StayingPageGroupSpacesSection', heading?: string | null, paragraphs?: any | null } | null, closingImage?: { __typename: 'StayingPageClosingImage', src?: string | null, alt?: string | null } | null };

export type IslandPagePartsFragment = { __typename: 'IslandPage', intro?: any | null, hero?: { __typename: 'IslandPageHero', image?: string | null, imageAlt?: string | null, title: string, subtitle?: string | null } | null, climateSection?: { __typename: 'IslandPageClimateSection', heading?: string | null, paragraphs?: any | null, image?: string | null, imageAlt?: string | null } | null, mountainsSection?: { __typename: 'IslandPageMountainsSection', heading?: string | null, paragraphs?: any | null, image?: string | null, imageAlt?: string | null } | null, wildlifeSection?: { __typename: 'IslandPageWildlifeSection', heading?: string | null, paragraphs?: any | null, image?: string | null, imageAlt?: string | null } | null };

export type RitualsPagePartsFragment = { __typename: 'RitualsPage', intro?: any | null, secondParagraphs?: any | null, hero?: { __typename: 'RitualsPageHero', image?: string | null, imageAlt?: string | null, title: string, subtitle?: string | null } | null, midImage?: { __typename: 'RitualsPageMidImage', src?: string | null, alt?: string | null } | null, shapedTogetherSection?: { __typename: 'RitualsPageShapedTogetherSection', heading?: string | null, paragraphs?: any | null, image?: string | null, imageAlt?: string | null } | null, gatheringsSection?: { __typename: 'RitualsPageGatheringsSection', heading?: string | null, paragraphs?: any | null, pullQuote?: string | null } | null };

export type ContactPagePartsFragment = { __typename: 'ContactPage', introText?: string | null, hero?: { __typename: 'ContactPageHero', image?: string | null, imageAlt?: string | null, title: string, subtitle?: string | null } | null };

export type HomePageQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type HomePageQuery = { __typename?: 'Query', homePage: { __typename: 'HomePage', id: string, poeticParagraphs?: any | null, secondParagraphs?: any | null, pullQuote?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, hero?: { __typename: 'HomePageHero', image?: string | null, imageAlt?: string | null, title: string, subtitle?: string | null } | null, mapCta?: { __typename: 'HomePageMapCta', heading?: string | null, description?: any | null } | null, firstImage?: { __typename: 'HomePageFirstImage', src?: string | null, alt?: string | null } | null, secondImage?: { __typename: 'HomePageSecondImage', src?: string | null, alt?: string | null } | null } };

export type HomePageConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<HomePageFilter>;
}>;


export type HomePageConnectionQuery = { __typename?: 'Query', homePageConnection: { __typename?: 'HomePageConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'HomePageConnectionEdges', cursor: string, node?: { __typename: 'HomePage', id: string, poeticParagraphs?: any | null, secondParagraphs?: any | null, pullQuote?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, hero?: { __typename: 'HomePageHero', image?: string | null, imageAlt?: string | null, title: string, subtitle?: string | null } | null, mapCta?: { __typename: 'HomePageMapCta', heading?: string | null, description?: any | null } | null, firstImage?: { __typename: 'HomePageFirstImage', src?: string | null, alt?: string | null } | null, secondImage?: { __typename: 'HomePageSecondImage', src?: string | null, alt?: string | null } | null } | null } | null> | null } };

export type ActivitiesPageQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type ActivitiesPageQuery = { __typename?: 'Query', activitiesPage: { __typename: 'ActivitiesPage', id: string, intro?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, hero?: { __typename: 'ActivitiesPageHero', image?: string | null, imageAlt?: string | null, title: string, subtitle?: string | null } | null, waterSection?: { __typename: 'ActivitiesPageWaterSection', heading?: string | null, items?: Array<{ __typename: 'ActivitiesPageWaterSectionItems', image?: string | null, imageAlt?: string | null, title?: string | null, description?: string | null } | null> | null } | null, landSection?: { __typename: 'ActivitiesPageLandSection', heading?: string | null, items?: Array<{ __typename: 'ActivitiesPageLandSectionItems', image?: string | null, imageAlt?: string | null, title?: string | null, description?: string | null } | null> | null } | null, regionSection?: { __typename: 'ActivitiesPageRegionSection', heading?: string | null, image?: string | null, imageAlt?: string | null, places?: Array<{ __typename: 'ActivitiesPageRegionSectionPlaces', name?: string | null, description?: any | null } | null> | null } | null, fireSection?: { __typename: 'ActivitiesPageFireSection', heading?: string | null, text?: any | null, closingImage?: string | null, closingImageAlt?: string | null } | null } };

export type ActivitiesPageConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<ActivitiesPageFilter>;
}>;


export type ActivitiesPageConnectionQuery = { __typename?: 'Query', activitiesPageConnection: { __typename?: 'ActivitiesPageConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'ActivitiesPageConnectionEdges', cursor: string, node?: { __typename: 'ActivitiesPage', id: string, intro?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, hero?: { __typename: 'ActivitiesPageHero', image?: string | null, imageAlt?: string | null, title: string, subtitle?: string | null } | null, waterSection?: { __typename: 'ActivitiesPageWaterSection', heading?: string | null, items?: Array<{ __typename: 'ActivitiesPageWaterSectionItems', image?: string | null, imageAlt?: string | null, title?: string | null, description?: string | null } | null> | null } | null, landSection?: { __typename: 'ActivitiesPageLandSection', heading?: string | null, items?: Array<{ __typename: 'ActivitiesPageLandSectionItems', image?: string | null, imageAlt?: string | null, title?: string | null, description?: string | null } | null> | null } | null, regionSection?: { __typename: 'ActivitiesPageRegionSection', heading?: string | null, image?: string | null, imageAlt?: string | null, places?: Array<{ __typename: 'ActivitiesPageRegionSectionPlaces', name?: string | null, description?: any | null } | null> | null } | null, fireSection?: { __typename: 'ActivitiesPageFireSection', heading?: string | null, text?: any | null, closingImage?: string | null, closingImageAlt?: string | null } | null } | null } | null> | null } };

export type StayingPageQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type StayingPageQuery = { __typename?: 'Query', stayingPage: { __typename: 'StayingPage', id: string, intro?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, hero?: { __typename: 'StayingPageHero', image?: string | null, imageAlt?: string | null, title: string, subtitle?: string | null } | null, buildingImages?: Array<{ __typename: 'StayingPageBuildingImages', src?: string | null, alt?: string | null } | null> | null, sleepingSection?: { __typename: 'StayingPageSleepingSection', heading?: string | null, paragraphs?: any | null, image?: string | null, imageAlt?: string | null } | null, sharedSpacesSection?: { __typename: 'StayingPageSharedSpacesSection', heading?: string | null, paragraphs?: any | null } | null, galleryImages?: Array<{ __typename: 'StayingPageGalleryImages', src?: string | null, alt?: string | null } | null> | null, groupSpacesSection?: { __typename: 'StayingPageGroupSpacesSection', heading?: string | null, paragraphs?: any | null } | null, closingImage?: { __typename: 'StayingPageClosingImage', src?: string | null, alt?: string | null } | null } };

export type StayingPageConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<StayingPageFilter>;
}>;


export type StayingPageConnectionQuery = { __typename?: 'Query', stayingPageConnection: { __typename?: 'StayingPageConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'StayingPageConnectionEdges', cursor: string, node?: { __typename: 'StayingPage', id: string, intro?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, hero?: { __typename: 'StayingPageHero', image?: string | null, imageAlt?: string | null, title: string, subtitle?: string | null } | null, buildingImages?: Array<{ __typename: 'StayingPageBuildingImages', src?: string | null, alt?: string | null } | null> | null, sleepingSection?: { __typename: 'StayingPageSleepingSection', heading?: string | null, paragraphs?: any | null, image?: string | null, imageAlt?: string | null } | null, sharedSpacesSection?: { __typename: 'StayingPageSharedSpacesSection', heading?: string | null, paragraphs?: any | null } | null, galleryImages?: Array<{ __typename: 'StayingPageGalleryImages', src?: string | null, alt?: string | null } | null> | null, groupSpacesSection?: { __typename: 'StayingPageGroupSpacesSection', heading?: string | null, paragraphs?: any | null } | null, closingImage?: { __typename: 'StayingPageClosingImage', src?: string | null, alt?: string | null } | null } | null } | null> | null } };

export type IslandPageQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type IslandPageQuery = { __typename?: 'Query', islandPage: { __typename: 'IslandPage', id: string, intro?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, hero?: { __typename: 'IslandPageHero', image?: string | null, imageAlt?: string | null, title: string, subtitle?: string | null } | null, climateSection?: { __typename: 'IslandPageClimateSection', heading?: string | null, paragraphs?: any | null, image?: string | null, imageAlt?: string | null } | null, mountainsSection?: { __typename: 'IslandPageMountainsSection', heading?: string | null, paragraphs?: any | null, image?: string | null, imageAlt?: string | null } | null, wildlifeSection?: { __typename: 'IslandPageWildlifeSection', heading?: string | null, paragraphs?: any | null, image?: string | null, imageAlt?: string | null } | null } };

export type IslandPageConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<IslandPageFilter>;
}>;


export type IslandPageConnectionQuery = { __typename?: 'Query', islandPageConnection: { __typename?: 'IslandPageConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'IslandPageConnectionEdges', cursor: string, node?: { __typename: 'IslandPage', id: string, intro?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, hero?: { __typename: 'IslandPageHero', image?: string | null, imageAlt?: string | null, title: string, subtitle?: string | null } | null, climateSection?: { __typename: 'IslandPageClimateSection', heading?: string | null, paragraphs?: any | null, image?: string | null, imageAlt?: string | null } | null, mountainsSection?: { __typename: 'IslandPageMountainsSection', heading?: string | null, paragraphs?: any | null, image?: string | null, imageAlt?: string | null } | null, wildlifeSection?: { __typename: 'IslandPageWildlifeSection', heading?: string | null, paragraphs?: any | null, image?: string | null, imageAlt?: string | null } | null } | null } | null> | null } };

export type RitualsPageQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type RitualsPageQuery = { __typename?: 'Query', ritualsPage: { __typename: 'RitualsPage', id: string, intro?: any | null, secondParagraphs?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, hero?: { __typename: 'RitualsPageHero', image?: string | null, imageAlt?: string | null, title: string, subtitle?: string | null } | null, midImage?: { __typename: 'RitualsPageMidImage', src?: string | null, alt?: string | null } | null, shapedTogetherSection?: { __typename: 'RitualsPageShapedTogetherSection', heading?: string | null, paragraphs?: any | null, image?: string | null, imageAlt?: string | null } | null, gatheringsSection?: { __typename: 'RitualsPageGatheringsSection', heading?: string | null, paragraphs?: any | null, pullQuote?: string | null } | null } };

export type RitualsPageConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<RitualsPageFilter>;
}>;


export type RitualsPageConnectionQuery = { __typename?: 'Query', ritualsPageConnection: { __typename?: 'RitualsPageConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'RitualsPageConnectionEdges', cursor: string, node?: { __typename: 'RitualsPage', id: string, intro?: any | null, secondParagraphs?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, hero?: { __typename: 'RitualsPageHero', image?: string | null, imageAlt?: string | null, title: string, subtitle?: string | null } | null, midImage?: { __typename: 'RitualsPageMidImage', src?: string | null, alt?: string | null } | null, shapedTogetherSection?: { __typename: 'RitualsPageShapedTogetherSection', heading?: string | null, paragraphs?: any | null, image?: string | null, imageAlt?: string | null } | null, gatheringsSection?: { __typename: 'RitualsPageGatheringsSection', heading?: string | null, paragraphs?: any | null, pullQuote?: string | null } | null } | null } | null> | null } };

export type ContactPageQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type ContactPageQuery = { __typename?: 'Query', contactPage: { __typename: 'ContactPage', id: string, introText?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, hero?: { __typename: 'ContactPageHero', image?: string | null, imageAlt?: string | null, title: string, subtitle?: string | null } | null } };

export type ContactPageConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<ContactPageFilter>;
}>;


export type ContactPageConnectionQuery = { __typename?: 'Query', contactPageConnection: { __typename?: 'ContactPageConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'ContactPageConnectionEdges', cursor: string, node?: { __typename: 'ContactPage', id: string, introText?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, hero?: { __typename: 'ContactPageHero', image?: string | null, imageAlt?: string | null, title: string, subtitle?: string | null } | null } | null } | null> | null } };

export const HomePagePartsFragmentDoc = gql`
    fragment HomePageParts on HomePage {
  __typename
  hero {
    __typename
    image
    imageAlt
    title
    subtitle
  }
  poeticParagraphs
  secondParagraphs
  pullQuote
  mapCta {
    __typename
    heading
    description
  }
  firstImage {
    __typename
    src
    alt
  }
  secondImage {
    __typename
    src
    alt
  }
}
    `;
export const ActivitiesPagePartsFragmentDoc = gql`
    fragment ActivitiesPageParts on ActivitiesPage {
  __typename
  hero {
    __typename
    image
    imageAlt
    title
    subtitle
  }
  intro
  waterSection {
    __typename
    heading
    items {
      __typename
      image
      imageAlt
      title
      description
    }
  }
  landSection {
    __typename
    heading
    items {
      __typename
      image
      imageAlt
      title
      description
    }
  }
  regionSection {
    __typename
    heading
    places {
      __typename
      name
      description
    }
    image
    imageAlt
  }
  fireSection {
    __typename
    heading
    text
    closingImage
    closingImageAlt
  }
}
    `;
export const StayingPagePartsFragmentDoc = gql`
    fragment StayingPageParts on StayingPage {
  __typename
  hero {
    __typename
    image
    imageAlt
    title
    subtitle
  }
  intro
  buildingImages {
    __typename
    src
    alt
  }
  sleepingSection {
    __typename
    heading
    paragraphs
    image
    imageAlt
  }
  sharedSpacesSection {
    __typename
    heading
    paragraphs
  }
  galleryImages {
    __typename
    src
    alt
  }
  groupSpacesSection {
    __typename
    heading
    paragraphs
  }
  closingImage {
    __typename
    src
    alt
  }
}
    `;
export const IslandPagePartsFragmentDoc = gql`
    fragment IslandPageParts on IslandPage {
  __typename
  hero {
    __typename
    image
    imageAlt
    title
    subtitle
  }
  intro
  climateSection {
    __typename
    heading
    paragraphs
    image
    imageAlt
  }
  mountainsSection {
    __typename
    heading
    paragraphs
    image
    imageAlt
  }
  wildlifeSection {
    __typename
    heading
    paragraphs
    image
    imageAlt
  }
}
    `;
export const RitualsPagePartsFragmentDoc = gql`
    fragment RitualsPageParts on RitualsPage {
  __typename
  hero {
    __typename
    image
    imageAlt
    title
    subtitle
  }
  intro
  midImage {
    __typename
    src
    alt
  }
  secondParagraphs
  shapedTogetherSection {
    __typename
    heading
    paragraphs
    image
    imageAlt
  }
  gatheringsSection {
    __typename
    heading
    paragraphs
    pullQuote
  }
}
    `;
export const ContactPagePartsFragmentDoc = gql`
    fragment ContactPageParts on ContactPage {
  __typename
  hero {
    __typename
    image
    imageAlt
    title
    subtitle
  }
  introText
}
    `;
export const HomePageDocument = gql`
    query homePage($relativePath: String!) {
  homePage(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...HomePageParts
  }
}
    ${HomePagePartsFragmentDoc}`;
export const HomePageConnectionDocument = gql`
    query homePageConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: HomePageFilter) {
  homePageConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...HomePageParts
      }
    }
  }
}
    ${HomePagePartsFragmentDoc}`;
export const ActivitiesPageDocument = gql`
    query activitiesPage($relativePath: String!) {
  activitiesPage(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...ActivitiesPageParts
  }
}
    ${ActivitiesPagePartsFragmentDoc}`;
export const ActivitiesPageConnectionDocument = gql`
    query activitiesPageConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: ActivitiesPageFilter) {
  activitiesPageConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...ActivitiesPageParts
      }
    }
  }
}
    ${ActivitiesPagePartsFragmentDoc}`;
export const StayingPageDocument = gql`
    query stayingPage($relativePath: String!) {
  stayingPage(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...StayingPageParts
  }
}
    ${StayingPagePartsFragmentDoc}`;
export const StayingPageConnectionDocument = gql`
    query stayingPageConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: StayingPageFilter) {
  stayingPageConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...StayingPageParts
      }
    }
  }
}
    ${StayingPagePartsFragmentDoc}`;
export const IslandPageDocument = gql`
    query islandPage($relativePath: String!) {
  islandPage(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...IslandPageParts
  }
}
    ${IslandPagePartsFragmentDoc}`;
export const IslandPageConnectionDocument = gql`
    query islandPageConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: IslandPageFilter) {
  islandPageConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...IslandPageParts
      }
    }
  }
}
    ${IslandPagePartsFragmentDoc}`;
export const RitualsPageDocument = gql`
    query ritualsPage($relativePath: String!) {
  ritualsPage(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...RitualsPageParts
  }
}
    ${RitualsPagePartsFragmentDoc}`;
export const RitualsPageConnectionDocument = gql`
    query ritualsPageConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: RitualsPageFilter) {
  ritualsPageConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...RitualsPageParts
      }
    }
  }
}
    ${RitualsPagePartsFragmentDoc}`;
export const ContactPageDocument = gql`
    query contactPage($relativePath: String!) {
  contactPage(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...ContactPageParts
  }
}
    ${ContactPagePartsFragmentDoc}`;
export const ContactPageConnectionDocument = gql`
    query contactPageConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: ContactPageFilter) {
  contactPageConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...ContactPageParts
      }
    }
  }
}
    ${ContactPagePartsFragmentDoc}`;
export type Requester<C= {}> = <R, V>(doc: DocumentNode, vars?: V, options?: C) => Promise<R>
  export function getSdk<C>(requester: Requester<C>) {
    return {
      homePage(variables: HomePageQueryVariables, options?: C): Promise<{data: HomePageQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: HomePageQueryVariables, query: string}> {
        return requester<{data: HomePageQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: HomePageQueryVariables, query: string}, HomePageQueryVariables>(HomePageDocument, variables, options);
      },
    homePageConnection(variables?: HomePageConnectionQueryVariables, options?: C): Promise<{data: HomePageConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: HomePageConnectionQueryVariables, query: string}> {
        return requester<{data: HomePageConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: HomePageConnectionQueryVariables, query: string}, HomePageConnectionQueryVariables>(HomePageConnectionDocument, variables, options);
      },
    activitiesPage(variables: ActivitiesPageQueryVariables, options?: C): Promise<{data: ActivitiesPageQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ActivitiesPageQueryVariables, query: string}> {
        return requester<{data: ActivitiesPageQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ActivitiesPageQueryVariables, query: string}, ActivitiesPageQueryVariables>(ActivitiesPageDocument, variables, options);
      },
    activitiesPageConnection(variables?: ActivitiesPageConnectionQueryVariables, options?: C): Promise<{data: ActivitiesPageConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ActivitiesPageConnectionQueryVariables, query: string}> {
        return requester<{data: ActivitiesPageConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ActivitiesPageConnectionQueryVariables, query: string}, ActivitiesPageConnectionQueryVariables>(ActivitiesPageConnectionDocument, variables, options);
      },
    stayingPage(variables: StayingPageQueryVariables, options?: C): Promise<{data: StayingPageQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: StayingPageQueryVariables, query: string}> {
        return requester<{data: StayingPageQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: StayingPageQueryVariables, query: string}, StayingPageQueryVariables>(StayingPageDocument, variables, options);
      },
    stayingPageConnection(variables?: StayingPageConnectionQueryVariables, options?: C): Promise<{data: StayingPageConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: StayingPageConnectionQueryVariables, query: string}> {
        return requester<{data: StayingPageConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: StayingPageConnectionQueryVariables, query: string}, StayingPageConnectionQueryVariables>(StayingPageConnectionDocument, variables, options);
      },
    islandPage(variables: IslandPageQueryVariables, options?: C): Promise<{data: IslandPageQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: IslandPageQueryVariables, query: string}> {
        return requester<{data: IslandPageQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: IslandPageQueryVariables, query: string}, IslandPageQueryVariables>(IslandPageDocument, variables, options);
      },
    islandPageConnection(variables?: IslandPageConnectionQueryVariables, options?: C): Promise<{data: IslandPageConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: IslandPageConnectionQueryVariables, query: string}> {
        return requester<{data: IslandPageConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: IslandPageConnectionQueryVariables, query: string}, IslandPageConnectionQueryVariables>(IslandPageConnectionDocument, variables, options);
      },
    ritualsPage(variables: RitualsPageQueryVariables, options?: C): Promise<{data: RitualsPageQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: RitualsPageQueryVariables, query: string}> {
        return requester<{data: RitualsPageQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: RitualsPageQueryVariables, query: string}, RitualsPageQueryVariables>(RitualsPageDocument, variables, options);
      },
    ritualsPageConnection(variables?: RitualsPageConnectionQueryVariables, options?: C): Promise<{data: RitualsPageConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: RitualsPageConnectionQueryVariables, query: string}> {
        return requester<{data: RitualsPageConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: RitualsPageConnectionQueryVariables, query: string}, RitualsPageConnectionQueryVariables>(RitualsPageConnectionDocument, variables, options);
      },
    contactPage(variables: ContactPageQueryVariables, options?: C): Promise<{data: ContactPageQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ContactPageQueryVariables, query: string}> {
        return requester<{data: ContactPageQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ContactPageQueryVariables, query: string}, ContactPageQueryVariables>(ContactPageDocument, variables, options);
      },
    contactPageConnection(variables?: ContactPageConnectionQueryVariables, options?: C): Promise<{data: ContactPageConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ContactPageConnectionQueryVariables, query: string}> {
        return requester<{data: ContactPageConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ContactPageConnectionQueryVariables, query: string}, ContactPageConnectionQueryVariables>(ContactPageConnectionDocument, variables, options);
      }
    };
  }
  export type Sdk = ReturnType<typeof getSdk>;

// TinaSDK generated code
import { createClient, TinaClient } from "tinacms/dist/client";

const generateRequester = (
  client: TinaClient,
) => {
  const requester: (
    doc: any,
    vars?: any,
    options?: {
      branch?: string,
      /**
       * Aside from `method` and `body`, all fetch options are passed
       * through to underlying fetch request
       */
      fetchOptions?: Omit<Parameters<typeof fetch>[1], 'body' | 'method'>,
    },
    client
  ) => Promise<any> = async (doc, vars, options) => {
    let url = client.apiUrl
    if (options?.branch) {
      const index = client.apiUrl.lastIndexOf('/')
      url = client.apiUrl.substring(0, index + 1) + options.branch
    }
    const data = await client.request({
      query: doc,
      variables: vars,
      url,
    }, options)

    return { data: data?.data, errors: data?.errors, query: doc, variables: vars || {} }
  }

  return requester
}

/**
 * @experimental this class can be used but may change in the future
 **/
export const ExperimentalGetTinaClient = () =>
  getSdk(
    generateRequester(
      createClient({
        url: "http://localhost:4001/graphql",
        queries,
      })
    )
  )

export const queries = (
  client: TinaClient,
) => {
  const requester = generateRequester(client)
  return getSdk(requester)
}

  